Additional config options
craigwatson/puppet-transmission pull request #2
Opened 2017-06-10 16:53 UTC by mergwyn

Add support for configuring:
	• user
	• group
	• port-forwarding-enabled
	• watch-dir

Allow absoltue directory names for *dir directives in config.

Tidy up handling of config file on ubuntu 16.04 where the homedir should be /home/user/config/transmission-daemon"

2017-09-05 07:25 UTC, craigwatson requested changes
Hi,

Thanks for the PR, there are a few issues which need to be fixed however.

I'd be more than happy to merge the PR once the comments have been addressed :)

Thanks,
Craig

2017-09-05 07:25 UTC, craigwatson commented on manifests/params.pp
> +  if ($::operatingsystem == 'Ubuntu' and versioncmp($::operatingsystemrelease, '16.04')) {
This is the old Puppet3 way of using facts. Please update this to use the new `$facts` hash.

2017-09-05 07:25 UTC, craigwatson commented on manifests/params.pp
> +    $config_dir  = "${::transmission::params::home_dir}"
Raw variables don't need to be quoted.

2017-09-05 07:25 UTC, craigwatson commented on templates/systemd.erb
>  User=debian-transmission
This will need to be removed if you're setting the user dynamically above.

2017-09-05 07:25 UTC, craigwatson commented on manifests/config.pp
> +    owner   => "${::transmission::user}",
Raw variables don't need to be quoted.

2017-09-06 16:10 UTC, mergwyn commented
Hi Craig, thanks for your comments.  I've made the changes you suggested (and worked out how to enable the facts has in puppet 3!).

2017-09-06 16:11 UTC, mergwyn commented
Sorry - closed the PR by mistake.

2018-05-30 14:20 UTC, craigwatson commented
This is being closed in favour of #3

2018-05-30 14:20 UTC, closed without merging